package:
  name: rusty_axe
  version: 0.5

source:
  git_url: https://github.com/bbrener1/rf_5
  git_depth: 1

requirements:
  build:

  run:
    - git
    - rust
    - python
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - scikit-learn
    - statsmodels
    - numba
    - pytables
    - python-igraph
    - leidenalg
    - scanpy
    - louvain
