package:
  name: rusty_axe
  version: 0.5

source:
  git_url: https://github.com/bbrener1/rf_5
  git_depth: 1

requirements:
  host:
    - rust

  build:
    - rust
    - git

  run:
    - python <=3.8
    - matplotlib >=3.4.2
    - scikit-learn
    - statsmodels
    - python-igraph
    - leidenalg
    - scanpy
