package:
  name: rusty_axe
  version: 0.66

source:
  git_url: https://github.com/bbrener1/rf_5
  git_depth: 1

requirements:
  host:
    - rust

  build:
    - rust
    - git
    - python-build
    - wheel
    - setuptools


  run:
    - matplotlib >=3.4.2
    - scikit-learn
    - python-igraph
    - leidenalg
    - umap-learn

  test:
    - run_test.py
